# 编译环境
language: node_js

# Node 版本
node_js:
  - "15"

# 安装依赖
install:
  - npm install

# 代码编译
script:
  - npm run docs
  - npm run release

# 发布配置
deploy:
  # 发布到 gh-pages
  - provider: pages
    local_dir: dist
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: main
  # 发布到 npm
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true
      branch: main